[tool.poetry]
name = "stacosys"
version = "3.3"
description = "STAtic COmmenting SYStem"
authors = ["Yax"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
pyrss2gen = "^1.1"
markdown = "^3.1.1"
requests = "^2.25.1"
coverage = "^6.5"
background = "^0.2.1"
Flask = "^2.1.1"
types-markdown = "^3.4.2.1"
pydal = "^20221110.1"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15"
mypy = "^0.991"
pytest = "^7.2.0"
coveralls = "^3.3.1"
pytest-cov = "^4.0.0"
black = "^22.10.0"
pyinstaller = "^5.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
