name: docker
on:
  push:
    branches: [ main ]
jobs:
  build_docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.13]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up rye
      uses: sksat/setup-rye@v0.8.0
    - name: Sync dependencies using rye
      run: |
        rye pin ${{ matrix.python-version }}
        rye sync
        rye build --wheel --out dist
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
