name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        run: poetry install
      - uses: usama2490/lintly-flake8-github-action@v1.1
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          # Additional arguments to be black compliant
          args: "--max-line-length=88 --extend-ignore=E203 --exclude=*/tests/*"