name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        run: poetry install
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: .
          plugins: flake8-spellcheck
          config: flake8.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
